M48
; DRILL file KiCad 10.0.4 date 2026-07-09T14:34:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-09T14:34:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X143.11Y-105.82
X148.89Y-105.82
T2
X131.495Y-127.4
X187.105Y-127.4
M30
